const TASKS = {
  LOAD: "TASKS_LOAD",
  ADD: "TASKS_ADD",
  DELETE: "TASKS_DELETE",
  TOGGLE: "TASKS_TOGGLE",
  UPDATE: "TASKS_UPDATE",
  LOAD_SUCCESS: "TASKS_LOAD_SUCCESS",
  LOAD_FAIL: "TASKS_LOAD_FAIL"
};

export { TASKS };
